name: Upload File

on:
  schedule:
    - cron: '30 3 * * *'   # 9:00 AM IST
    - cron: '30 7 * * *'   # 1:00 PM IST
  workflow_dispatch:

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - run: npm ci

      - run: npx playwright install --with-deps

      - run: npx playwright test

        env:
          USERNAME: ${{ secrets.NAUKRI_USERNAME }}
          PASSWORD: ${{ secrets.NAUKRI_PASSWORD }}